export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  SCENE_FIXTURE_MISSING: "SCENE_FIXTURE_MISSING",
  SCENE_DURATION_INVALID: "SCENE_DURATION_INVALID",
  SCENE_SEQUENCE_DUPLICATE: "SCENE_SEQUENCE_DUPLICATE",
  SCENE_NAME_EMPTY: "SCENE_NAME_EMPTY",
  SCENE_ARCHIVE_IN_USE: "SCENE_ARCHIVE_IN_USE",
  SCENE_NOT_FOUND: "SCENE_NOT_FOUND",
  TRACK_TARGET_ARCHIVED: "TRACK_TARGET_ARCHIVED"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
